spring:
  # 服务发现
  cloud:
    nacos:
      discovery:
        server-addr: 121.36.229.15:8848
  redis:
    host: 81.68.236.154
    password: lif314
    port: 6379
  # 模块名
  application:
    name: gulimall-auth-server

server:
  port: 9200
